package com.bishe.smartcommunity.visitor.mapper;

import com.bishe.smartcommunity.visitor.domain.Visitors;
import com.bishe.smartcommunity.visitor.domain.VisitorsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VisitorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    long countByExample(VisitorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    int deleteByExample(VisitorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    int deleteByPrimaryKey(Integer visiteeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    int insert(Visitors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    int insertSelective(Visitors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    List<Visitors> selectByExample(VisitorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    Visitors selectByPrimaryKey(Integer visiteeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    int updateByExampleSelective(@Param("record") Visitors record, @Param("example") VisitorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    int updateByExample(@Param("record") Visitors record, @Param("example") VisitorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    int updateByPrimaryKeySelective(Visitors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitors
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    int updateByPrimaryKey(Visitors record);
}