package com.bishe.smartcommunity.property.mapper;

import com.bishe.smartcommunity.property.domain.Voting;
import com.bishe.smartcommunity.property.domain.VotingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VotingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    long countByExample(VotingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    int deleteByExample(VotingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    int deleteByPrimaryKey(Integer voteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    int insert(Voting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    int insertSelective(Voting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    List<Voting> selectByExample(VotingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    Voting selectByPrimaryKey(Integer voteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    int updateByExampleSelective(@Param("record") Voting record, @Param("example") VotingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    int updateByExample(@Param("record") Voting record, @Param("example") VotingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    int updateByPrimaryKeySelective(Voting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    int updateByPrimaryKey(Voting record);
}