#整合mybatis-plus
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*.xml
#  global-config:
#    db-config:
#      id-type: auto


#配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sc_resident?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: smartcommunity-resident
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
#设置端口
server:
  port: 8000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bishe.smartcommunity.resident.domain
