package com.bishe.smartcommunity.property.domain;

import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;
@Repository
public class PropertyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public PropertyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPropertyIdIsNull() {
            addCriterion("property_id is null");
            return (Criteria) this;
        }

        public Criteria andPropertyIdIsNotNull() {
            addCriterion("property_id is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyIdEqualTo(Integer value) {
            addCriterion("property_id =", value, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdNotEqualTo(Integer value) {
            addCriterion("property_id <>", value, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdGreaterThan(Integer value) {
            addCriterion("property_id >", value, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("property_id >=", value, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdLessThan(Integer value) {
            addCriterion("property_id <", value, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdLessThanOrEqualTo(Integer value) {
            addCriterion("property_id <=", value, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdIn(List<Integer> values) {
            addCriterion("property_id in", values, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdNotIn(List<Integer> values) {
            addCriterion("property_id not in", values, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdBetween(Integer value1, Integer value2) {
            addCriterion("property_id between", value1, value2, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("property_id not between", value1, value2, "propertyId");
            return (Criteria) this;
        }

        public Criteria andPropertyNameIsNull() {
            addCriterion("property_name is null");
            return (Criteria) this;
        }

        public Criteria andPropertyNameIsNotNull() {
            addCriterion("property_name is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyNameEqualTo(String value) {
            addCriterion("property_name =", value, "propertyName");
            return (Criteria) this;
        }

        public Criteria andPropertyNameNotEqualTo(String value) {
            addCriterion("property_name <>", value, "propertyName");
            return (Criteria) this;
        }

        public Criteria andPropertyNameGreaterThan(String value) {
            addCriterion("property_name >", value, "propertyName");
            return (Criteria) this;
        }

        public Criteria andPropertyNameGreaterThanOrEqualTo(String value) {
            addCriterion("property_name >=", value, "propertyName");
            return (Criteria) this;
        }

        public Criteria andPropertyNameLessThan(String value) {
            addCriterion("property_name <", value, "propertyName");
            return (Criteria) this;
        }

        public Criteria andPropertyNameLessThanOrEqualTo(String value) {
            addCriterion("property_name <=", value, "propertyName");
            return (Criteria) this;
        }

        public Criteria andPropertyNameLike(String value) {
            addCriterion("property_name like", value, "propertyName");
            return (Criteria) this;
        }

        public Criteria andPropertyNameNotLike(String value) {
            addCriterion("property_name not like", value, "propertyName");
            return (Criteria) this;
        }

        public Criteria andPropertyNameIn(List<String> values) {
            addCriterion("property_name in", values, "propertyName");
            return (Criteria) this;
        }

        public Criteria andPropertyNameNotIn(List<String> values) {
            addCriterion("property_name not in", values, "propertyName");
            return (Criteria) this;
        }

        public Criteria andPropertyNameBetween(String value1, String value2) {
            addCriterion("property_name between", value1, value2, "propertyName");
            return (Criteria) this;
        }

        public Criteria andPropertyNameNotBetween(String value1, String value2) {
            addCriterion("property_name not between", value1, value2, "propertyName");
            return (Criteria) this;
        }

        public Criteria andPropertyPwdIsNull() {
            addCriterion("property_pwd is null");
            return (Criteria) this;
        }

        public Criteria andPropertyPwdIsNotNull() {
            addCriterion("property_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyPwdEqualTo(String value) {
            addCriterion("property_pwd =", value, "propertyPwd");
            return (Criteria) this;
        }

        public Criteria andPropertyPwdNotEqualTo(String value) {
            addCriterion("property_pwd <>", value, "propertyPwd");
            return (Criteria) this;
        }

        public Criteria andPropertyPwdGreaterThan(String value) {
            addCriterion("property_pwd >", value, "propertyPwd");
            return (Criteria) this;
        }

        public Criteria andPropertyPwdGreaterThanOrEqualTo(String value) {
            addCriterion("property_pwd >=", value, "propertyPwd");
            return (Criteria) this;
        }

        public Criteria andPropertyPwdLessThan(String value) {
            addCriterion("property_pwd <", value, "propertyPwd");
            return (Criteria) this;
        }

        public Criteria andPropertyPwdLessThanOrEqualTo(String value) {
            addCriterion("property_pwd <=", value, "propertyPwd");
            return (Criteria) this;
        }

        public Criteria andPropertyPwdLike(String value) {
            addCriterion("property_pwd like", value, "propertyPwd");
            return (Criteria) this;
        }

        public Criteria andPropertyPwdNotLike(String value) {
            addCriterion("property_pwd not like", value, "propertyPwd");
            return (Criteria) this;
        }

        public Criteria andPropertyPwdIn(List<String> values) {
            addCriterion("property_pwd in", values, "propertyPwd");
            return (Criteria) this;
        }

        public Criteria andPropertyPwdNotIn(List<String> values) {
            addCriterion("property_pwd not in", values, "propertyPwd");
            return (Criteria) this;
        }

        public Criteria andPropertyPwdBetween(String value1, String value2) {
            addCriterion("property_pwd between", value1, value2, "propertyPwd");
            return (Criteria) this;
        }

        public Criteria andPropertyPwdNotBetween(String value1, String value2) {
            addCriterion("property_pwd not between", value1, value2, "propertyPwd");
            return (Criteria) this;
        }

        public Criteria andPropertyPhoneIsNull() {
            addCriterion("property_phone is null");
            return (Criteria) this;
        }

        public Criteria andPropertyPhoneIsNotNull() {
            addCriterion("property_phone is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyPhoneEqualTo(String value) {
            addCriterion("property_phone =", value, "propertyPhone");
            return (Criteria) this;
        }

        public Criteria andPropertyPhoneNotEqualTo(String value) {
            addCriterion("property_phone <>", value, "propertyPhone");
            return (Criteria) this;
        }

        public Criteria andPropertyPhoneGreaterThan(String value) {
            addCriterion("property_phone >", value, "propertyPhone");
            return (Criteria) this;
        }

        public Criteria andPropertyPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("property_phone >=", value, "propertyPhone");
            return (Criteria) this;
        }

        public Criteria andPropertyPhoneLessThan(String value) {
            addCriterion("property_phone <", value, "propertyPhone");
            return (Criteria) this;
        }

        public Criteria andPropertyPhoneLessThanOrEqualTo(String value) {
            addCriterion("property_phone <=", value, "propertyPhone");
            return (Criteria) this;
        }

        public Criteria andPropertyPhoneLike(String value) {
            addCriterion("property_phone like", value, "propertyPhone");
            return (Criteria) this;
        }

        public Criteria andPropertyPhoneNotLike(String value) {
            addCriterion("property_phone not like", value, "propertyPhone");
            return (Criteria) this;
        }

        public Criteria andPropertyPhoneIn(List<String> values) {
            addCriterion("property_phone in", values, "propertyPhone");
            return (Criteria) this;
        }

        public Criteria andPropertyPhoneNotIn(List<String> values) {
            addCriterion("property_phone not in", values, "propertyPhone");
            return (Criteria) this;
        }

        public Criteria andPropertyPhoneBetween(String value1, String value2) {
            addCriterion("property_phone between", value1, value2, "propertyPhone");
            return (Criteria) this;
        }

        public Criteria andPropertyPhoneNotBetween(String value1, String value2) {
            addCriterion("property_phone not between", value1, value2, "propertyPhone");
            return (Criteria) this;
        }

        public Criteria andPropertyStateIsNull() {
            addCriterion("property_state is null");
            return (Criteria) this;
        }

        public Criteria andPropertyStateIsNotNull() {
            addCriterion("property_state is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyStateEqualTo(Integer value) {
            addCriterion("property_state =", value, "propertyState");
            return (Criteria) this;
        }

        public Criteria andPropertyStateNotEqualTo(Integer value) {
            addCriterion("property_state <>", value, "propertyState");
            return (Criteria) this;
        }

        public Criteria andPropertyStateGreaterThan(Integer value) {
            addCriterion("property_state >", value, "propertyState");
            return (Criteria) this;
        }

        public Criteria andPropertyStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("property_state >=", value, "propertyState");
            return (Criteria) this;
        }

        public Criteria andPropertyStateLessThan(Integer value) {
            addCriterion("property_state <", value, "propertyState");
            return (Criteria) this;
        }

        public Criteria andPropertyStateLessThanOrEqualTo(Integer value) {
            addCriterion("property_state <=", value, "propertyState");
            return (Criteria) this;
        }

        public Criteria andPropertyStateIn(List<Integer> values) {
            addCriterion("property_state in", values, "propertyState");
            return (Criteria) this;
        }

        public Criteria andPropertyStateNotIn(List<Integer> values) {
            addCriterion("property_state not in", values, "propertyState");
            return (Criteria) this;
        }

        public Criteria andPropertyStateBetween(Integer value1, Integer value2) {
            addCriterion("property_state between", value1, value2, "propertyState");
            return (Criteria) this;
        }

        public Criteria andPropertyStateNotBetween(Integer value1, Integer value2) {
            addCriterion("property_state not between", value1, value2, "propertyState");
            return (Criteria) this;
        }

        public Criteria andPropertyScoreIsNull() {
            addCriterion("Property_score is null");
            return (Criteria) this;
        }

        public Criteria andPropertyScoreIsNotNull() {
            addCriterion("Property_score is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyScoreEqualTo(Integer value) {
            addCriterion("Property_score =", value, "propertyScore");
            return (Criteria) this;
        }

        public Criteria andPropertyScoreNotEqualTo(Integer value) {
            addCriterion("Property_score <>", value, "propertyScore");
            return (Criteria) this;
        }

        public Criteria andPropertyScoreGreaterThan(Integer value) {
            addCriterion("Property_score >", value, "propertyScore");
            return (Criteria) this;
        }

        public Criteria andPropertyScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("Property_score >=", value, "propertyScore");
            return (Criteria) this;
        }

        public Criteria andPropertyScoreLessThan(Integer value) {
            addCriterion("Property_score <", value, "propertyScore");
            return (Criteria) this;
        }

        public Criteria andPropertyScoreLessThanOrEqualTo(Integer value) {
            addCriterion("Property_score <=", value, "propertyScore");
            return (Criteria) this;
        }

        public Criteria andPropertyScoreIn(List<Integer> values) {
            addCriterion("Property_score in", values, "propertyScore");
            return (Criteria) this;
        }

        public Criteria andPropertyScoreNotIn(List<Integer> values) {
            addCriterion("Property_score not in", values, "propertyScore");
            return (Criteria) this;
        }

        public Criteria andPropertyScoreBetween(Integer value1, Integer value2) {
            addCriterion("Property_score between", value1, value2, "propertyScore");
            return (Criteria) this;
        }

        public Criteria andPropertyScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("Property_score not between", value1, value2, "propertyScore");
            return (Criteria) this;
        }

        public Criteria andPropertyTaskIsNull() {
            addCriterion("Property_task is null");
            return (Criteria) this;
        }

        public Criteria andPropertyTaskIsNotNull() {
            addCriterion("Property_task is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyTaskEqualTo(Integer value) {
            addCriterion("Property_task =", value, "propertyTask");
            return (Criteria) this;
        }

        public Criteria andPropertyTaskNotEqualTo(Integer value) {
            addCriterion("Property_task <>", value, "propertyTask");
            return (Criteria) this;
        }

        public Criteria andPropertyTaskGreaterThan(Integer value) {
            addCriterion("Property_task >", value, "propertyTask");
            return (Criteria) this;
        }

        public Criteria andPropertyTaskGreaterThanOrEqualTo(Integer value) {
            addCriterion("Property_task >=", value, "propertyTask");
            return (Criteria) this;
        }

        public Criteria andPropertyTaskLessThan(Integer value) {
            addCriterion("Property_task <", value, "propertyTask");
            return (Criteria) this;
        }

        public Criteria andPropertyTaskLessThanOrEqualTo(Integer value) {
            addCriterion("Property_task <=", value, "propertyTask");
            return (Criteria) this;
        }

        public Criteria andPropertyTaskIn(List<Integer> values) {
            addCriterion("Property_task in", values, "propertyTask");
            return (Criteria) this;
        }

        public Criteria andPropertyTaskNotIn(List<Integer> values) {
            addCriterion("Property_task not in", values, "propertyTask");
            return (Criteria) this;
        }

        public Criteria andPropertyTaskBetween(Integer value1, Integer value2) {
            addCriterion("Property_task between", value1, value2, "propertyTask");
            return (Criteria) this;
        }

        public Criteria andPropertyTaskNotBetween(Integer value1, Integer value2) {
            addCriterion("Property_task not between", value1, value2, "propertyTask");
            return (Criteria) this;
        }

        public Criteria andPropertyNoticeIsNull() {
            addCriterion("property_notice is null");
            return (Criteria) this;
        }

        public Criteria andPropertyNoticeIsNotNull() {
            addCriterion("property_notice is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyNoticeEqualTo(String value) {
            addCriterion("property_notice =", value, "propertyNotice");
            return (Criteria) this;
        }

        public Criteria andPropertyNoticeNotEqualTo(String value) {
            addCriterion("property_notice <>", value, "propertyNotice");
            return (Criteria) this;
        }

        public Criteria andPropertyNoticeGreaterThan(String value) {
            addCriterion("property_notice >", value, "propertyNotice");
            return (Criteria) this;
        }

        public Criteria andPropertyNoticeGreaterThanOrEqualTo(String value) {
            addCriterion("property_notice >=", value, "propertyNotice");
            return (Criteria) this;
        }

        public Criteria andPropertyNoticeLessThan(String value) {
            addCriterion("property_notice <", value, "propertyNotice");
            return (Criteria) this;
        }

        public Criteria andPropertyNoticeLessThanOrEqualTo(String value) {
            addCriterion("property_notice <=", value, "propertyNotice");
            return (Criteria) this;
        }

        public Criteria andPropertyNoticeLike(String value) {
            addCriterion("property_notice like", value, "propertyNotice");
            return (Criteria) this;
        }

        public Criteria andPropertyNoticeNotLike(String value) {
            addCriterion("property_notice not like", value, "propertyNotice");
            return (Criteria) this;
        }

        public Criteria andPropertyNoticeIn(List<String> values) {
            addCriterion("property_notice in", values, "propertyNotice");
            return (Criteria) this;
        }

        public Criteria andPropertyNoticeNotIn(List<String> values) {
            addCriterion("property_notice not in", values, "propertyNotice");
            return (Criteria) this;
        }

        public Criteria andPropertyNoticeBetween(String value1, String value2) {
            addCriterion("property_notice between", value1, value2, "propertyNotice");
            return (Criteria) this;
        }

        public Criteria andPropertyNoticeNotBetween(String value1, String value2) {
            addCriterion("property_notice not between", value1, value2, "propertyNotice");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table property
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 08 12:53:52 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table property
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}