package com.bishe.smartcommunity.property.domain;

import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;
@Repository
public class VotingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public VotingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVoteIdIsNull() {
            addCriterion("vote_id is null");
            return (Criteria) this;
        }

        public Criteria andVoteIdIsNotNull() {
            addCriterion("vote_id is not null");
            return (Criteria) this;
        }

        public Criteria andVoteIdEqualTo(Integer value) {
            addCriterion("vote_id =", value, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdNotEqualTo(Integer value) {
            addCriterion("vote_id <>", value, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdGreaterThan(Integer value) {
            addCriterion("vote_id >", value, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vote_id >=", value, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdLessThan(Integer value) {
            addCriterion("vote_id <", value, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdLessThanOrEqualTo(Integer value) {
            addCriterion("vote_id <=", value, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdIn(List<Integer> values) {
            addCriterion("vote_id in", values, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdNotIn(List<Integer> values) {
            addCriterion("vote_id not in", values, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdBetween(Integer value1, Integer value2) {
            addCriterion("vote_id between", value1, value2, "voteId");
            return (Criteria) this;
        }

        public Criteria andVoteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vote_id not between", value1, value2, "voteId");
            return (Criteria) this;
        }

        public Criteria andSunmmaryIsNull() {
            addCriterion("sunmmary is null");
            return (Criteria) this;
        }

        public Criteria andSunmmaryIsNotNull() {
            addCriterion("sunmmary is not null");
            return (Criteria) this;
        }

        public Criteria andSunmmaryEqualTo(String value) {
            addCriterion("sunmmary =", value, "sunmmary");
            return (Criteria) this;
        }

        public Criteria andSunmmaryNotEqualTo(String value) {
            addCriterion("sunmmary <>", value, "sunmmary");
            return (Criteria) this;
        }

        public Criteria andSunmmaryGreaterThan(String value) {
            addCriterion("sunmmary >", value, "sunmmary");
            return (Criteria) this;
        }

        public Criteria andSunmmaryGreaterThanOrEqualTo(String value) {
            addCriterion("sunmmary >=", value, "sunmmary");
            return (Criteria) this;
        }

        public Criteria andSunmmaryLessThan(String value) {
            addCriterion("sunmmary <", value, "sunmmary");
            return (Criteria) this;
        }

        public Criteria andSunmmaryLessThanOrEqualTo(String value) {
            addCriterion("sunmmary <=", value, "sunmmary");
            return (Criteria) this;
        }

        public Criteria andSunmmaryLike(String value) {
            addCriterion("sunmmary like", value, "sunmmary");
            return (Criteria) this;
        }

        public Criteria andSunmmaryNotLike(String value) {
            addCriterion("sunmmary not like", value, "sunmmary");
            return (Criteria) this;
        }

        public Criteria andSunmmaryIn(List<String> values) {
            addCriterion("sunmmary in", values, "sunmmary");
            return (Criteria) this;
        }

        public Criteria andSunmmaryNotIn(List<String> values) {
            addCriterion("sunmmary not in", values, "sunmmary");
            return (Criteria) this;
        }

        public Criteria andSunmmaryBetween(String value1, String value2) {
            addCriterion("sunmmary between", value1, value2, "sunmmary");
            return (Criteria) this;
        }

        public Criteria andSunmmaryNotBetween(String value1, String value2) {
            addCriterion("sunmmary not between", value1, value2, "sunmmary");
            return (Criteria) this;
        }

        public Criteria andSupportIsNull() {
            addCriterion("support is null");
            return (Criteria) this;
        }

        public Criteria andSupportIsNotNull() {
            addCriterion("support is not null");
            return (Criteria) this;
        }

        public Criteria andSupportEqualTo(Integer value) {
            addCriterion("support =", value, "support");
            return (Criteria) this;
        }

        public Criteria andSupportNotEqualTo(Integer value) {
            addCriterion("support <>", value, "support");
            return (Criteria) this;
        }

        public Criteria andSupportGreaterThan(Integer value) {
            addCriterion("support >", value, "support");
            return (Criteria) this;
        }

        public Criteria andSupportGreaterThanOrEqualTo(Integer value) {
            addCriterion("support >=", value, "support");
            return (Criteria) this;
        }

        public Criteria andSupportLessThan(Integer value) {
            addCriterion("support <", value, "support");
            return (Criteria) this;
        }

        public Criteria andSupportLessThanOrEqualTo(Integer value) {
            addCriterion("support <=", value, "support");
            return (Criteria) this;
        }

        public Criteria andSupportIn(List<Integer> values) {
            addCriterion("support in", values, "support");
            return (Criteria) this;
        }

        public Criteria andSupportNotIn(List<Integer> values) {
            addCriterion("support not in", values, "support");
            return (Criteria) this;
        }

        public Criteria andSupportBetween(Integer value1, Integer value2) {
            addCriterion("support between", value1, value2, "support");
            return (Criteria) this;
        }

        public Criteria andSupportNotBetween(Integer value1, Integer value2) {
            addCriterion("support not between", value1, value2, "support");
            return (Criteria) this;
        }

        public Criteria andOpposeIsNull() {
            addCriterion("oppose is null");
            return (Criteria) this;
        }

        public Criteria andOpposeIsNotNull() {
            addCriterion("oppose is not null");
            return (Criteria) this;
        }

        public Criteria andOpposeEqualTo(Integer value) {
            addCriterion("oppose =", value, "oppose");
            return (Criteria) this;
        }

        public Criteria andOpposeNotEqualTo(Integer value) {
            addCriterion("oppose <>", value, "oppose");
            return (Criteria) this;
        }

        public Criteria andOpposeGreaterThan(Integer value) {
            addCriterion("oppose >", value, "oppose");
            return (Criteria) this;
        }

        public Criteria andOpposeGreaterThanOrEqualTo(Integer value) {
            addCriterion("oppose >=", value, "oppose");
            return (Criteria) this;
        }

        public Criteria andOpposeLessThan(Integer value) {
            addCriterion("oppose <", value, "oppose");
            return (Criteria) this;
        }

        public Criteria andOpposeLessThanOrEqualTo(Integer value) {
            addCriterion("oppose <=", value, "oppose");
            return (Criteria) this;
        }

        public Criteria andOpposeIn(List<Integer> values) {
            addCriterion("oppose in", values, "oppose");
            return (Criteria) this;
        }

        public Criteria andOpposeNotIn(List<Integer> values) {
            addCriterion("oppose not in", values, "oppose");
            return (Criteria) this;
        }

        public Criteria andOpposeBetween(Integer value1, Integer value2) {
            addCriterion("oppose between", value1, value2, "oppose");
            return (Criteria) this;
        }

        public Criteria andOpposeNotBetween(Integer value1, Integer value2) {
            addCriterion("oppose not between", value1, value2, "oppose");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table voting
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 08 12:53:52 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}