package com.bishe.smartcommunity.property.domain;

import java.io.Serializable;

public class Voting implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voting.vote_id
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    private Integer voteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voting.sunmmary
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    private String sunmmary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voting.support
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    private Integer support;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voting.oppose
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    private Integer oppose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voting
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voting.vote_id
     *
     * @return the value of voting.vote_id
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public Integer getVoteId() {
        return voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voting.vote_id
     *
     * @param voteId the value for voting.vote_id
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public void setVoteId(Integer voteId) {
        this.voteId = voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voting.sunmmary
     *
     * @return the value of voting.sunmmary
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public String getSunmmary() {
        return sunmmary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voting.sunmmary
     *
     * @param sunmmary the value for voting.sunmmary
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public void setSunmmary(String sunmmary) {
        this.sunmmary = sunmmary == null ? null : sunmmary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voting.support
     *
     * @return the value of voting.support
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public Integer getSupport() {
        return support;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voting.support
     *
     * @param support the value for voting.support
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public void setSupport(Integer support) {
        this.support = support;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voting.oppose
     *
     * @return the value of voting.oppose
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public Integer getOppose() {
        return oppose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voting.oppose
     *
     * @param oppose the value for voting.oppose
     *
     * @mbg.generated Mon Mar 08 12:53:52 CST 2021
     */
    public void setOppose(Integer oppose) {
        this.oppose = oppose;
    }
}