package com.bishe.smartcommunity.visitor.domain;

import org.springframework.stereotype.Repository;

import java.io.Serializable;
@Repository
public class Visitors implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.visitee_id
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    private Integer visiteeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.visitor_id
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    private Integer visitorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.visitor_name
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    private String visitorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitors.visitor_state
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    private Integer visitorState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table visitors
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.visitee_id
     *
     * @return the value of visitors.visitee_id
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    public Integer getVisiteeId() {
        return visiteeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.visitee_id
     *
     * @param visiteeId the value for visitors.visitee_id
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    public void setVisiteeId(Integer visiteeId) {
        this.visiteeId = visiteeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.visitor_id
     *
     * @return the value of visitors.visitor_id
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    public Integer getVisitorId() {
        return visitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.visitor_id
     *
     * @param visitorId the value for visitors.visitor_id
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    public void setVisitorId(Integer visitorId) {
        this.visitorId = visitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.visitor_name
     *
     * @return the value of visitors.visitor_name
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    public String getVisitorName() {
        return visitorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.visitor_name
     *
     * @param visitorName the value for visitors.visitor_name
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    public void setVisitorName(String visitorName) {
        this.visitorName = visitorName == null ? null : visitorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitors.visitor_state
     *
     * @return the value of visitors.visitor_state
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    public Integer getVisitorState() {
        return visitorState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitors.visitor_state
     *
     * @param visitorState the value for visitors.visitor_state
     *
     * @mbg.generated Mon Mar 08 15:20:02 CST 2021
     */
    public void setVisitorState(Integer visitorState) {
        this.visitorState = visitorState;
    }
}