package com.bishe.smartcommunity.resident.domain;

import java.io.Serializable;
import java.util.Date;

public class Task implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_id
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_name
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_state
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    private Integer taskState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_introduction
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    private String taskIntroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_created
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    private Date taskCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_description
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    private String taskDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_initiatorID
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    private Integer taskInitiatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_sovlerID
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    private Integer taskSovlerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_score
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    private Integer taskScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_id
     *
     * @return the value of task.task_id
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_id
     *
     * @param taskId the value for task.task_id
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_name
     *
     * @return the value of task.task_name
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_name
     *
     * @param taskName the value for task.task_name
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_state
     *
     * @return the value of task.task_state
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public Integer getTaskState() {
        return taskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_state
     *
     * @param taskState the value for task.task_state
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public void setTaskState(Integer taskState) {
        this.taskState = taskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_introduction
     *
     * @return the value of task.task_introduction
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public String getTaskIntroduction() {
        return taskIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_introduction
     *
     * @param taskIntroduction the value for task.task_introduction
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public void setTaskIntroduction(String taskIntroduction) {
        this.taskIntroduction = taskIntroduction == null ? null : taskIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_created
     *
     * @return the value of task.task_created
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public Date getTaskCreated() {
        return taskCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_created
     *
     * @param taskCreated the value for task.task_created
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public void setTaskCreated(Date taskCreated) {
        this.taskCreated = taskCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_description
     *
     * @return the value of task.task_description
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public String getTaskDescription() {
        return taskDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_description
     *
     * @param taskDescription the value for task.task_description
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public void setTaskDescription(String taskDescription) {
        this.taskDescription = taskDescription == null ? null : taskDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_initiatorID
     *
     * @return the value of task.task_initiatorID
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public Integer getTaskInitiatorid() {
        return taskInitiatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_initiatorID
     *
     * @param taskInitiatorid the value for task.task_initiatorID
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public void setTaskInitiatorid(Integer taskInitiatorid) {
        this.taskInitiatorid = taskInitiatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_sovlerID
     *
     * @return the value of task.task_sovlerID
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public Integer getTaskSovlerid() {
        return taskSovlerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_sovlerID
     *
     * @param taskSovlerid the value for task.task_sovlerID
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public void setTaskSovlerid(Integer taskSovlerid) {
        this.taskSovlerid = taskSovlerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_score
     *
     * @return the value of task.task_score
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public Integer getTaskScore() {
        return taskScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_score
     *
     * @param taskScore the value for task.task_score
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    public void setTaskScore(Integer taskScore) {
        this.taskScore = taskScore;
    }
}