package com.bishe.smartcommunity.resident.mapper;

import com.bishe.smartcommunity.resident.domain.Resident;
import com.bishe.smartcommunity.resident.domain.ResidentExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface ResidentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resident
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    long countByExample(ResidentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resident
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    int deleteByExample(ResidentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resident
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    int deleteByPrimaryKey(Integer residentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resident
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    int insert(Resident record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resident
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    int insertSelective(Resident record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resident
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    List<Resident> selectByExample(ResidentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resident
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    Resident selectByPrimaryKey(Integer residentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resident
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    int updateByExampleSelective(@Param("record") Resident record, @Param("example") ResidentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resident
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    int updateByExample(@Param("record") Resident record, @Param("example") ResidentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resident
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    int updateByPrimaryKeySelective(Resident record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resident
     *
     * @mbg.generated Mon Mar 08 13:49:10 CST 2021
     */
    int updateByPrimaryKey(Resident record);

    List<Resident> findAllResidents();
}