package com.bishe.smartcommunity.vehicle.domain;

import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;
@Repository
public class VehicleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public VehicleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVehicleIdIsNull() {
            addCriterion("vehicle_id is null");
            return (Criteria) this;
        }

        public Criteria andVehicleIdIsNotNull() {
            addCriterion("vehicle_id is not null");
            return (Criteria) this;
        }

        public Criteria andVehicleIdEqualTo(Integer value) {
            addCriterion("vehicle_id =", value, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdNotEqualTo(Integer value) {
            addCriterion("vehicle_id <>", value, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdGreaterThan(Integer value) {
            addCriterion("vehicle_id >", value, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vehicle_id >=", value, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdLessThan(Integer value) {
            addCriterion("vehicle_id <", value, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdLessThanOrEqualTo(Integer value) {
            addCriterion("vehicle_id <=", value, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdIn(List<Integer> values) {
            addCriterion("vehicle_id in", values, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdNotIn(List<Integer> values) {
            addCriterion("vehicle_id not in", values, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdBetween(Integer value1, Integer value2) {
            addCriterion("vehicle_id between", value1, value2, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vehicle_id not between", value1, value2, "vehicleId");
            return (Criteria) this;
        }

        public Criteria andVehicleOwnerIdIsNull() {
            addCriterion("vehicle_owner_ID is null");
            return (Criteria) this;
        }

        public Criteria andVehicleOwnerIdIsNotNull() {
            addCriterion("vehicle_owner_ID is not null");
            return (Criteria) this;
        }

        public Criteria andVehicleOwnerIdEqualTo(Integer value) {
            addCriterion("vehicle_owner_ID =", value, "vehicleOwnerId");
            return (Criteria) this;
        }

        public Criteria andVehicleOwnerIdNotEqualTo(Integer value) {
            addCriterion("vehicle_owner_ID <>", value, "vehicleOwnerId");
            return (Criteria) this;
        }

        public Criteria andVehicleOwnerIdGreaterThan(Integer value) {
            addCriterion("vehicle_owner_ID >", value, "vehicleOwnerId");
            return (Criteria) this;
        }

        public Criteria andVehicleOwnerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vehicle_owner_ID >=", value, "vehicleOwnerId");
            return (Criteria) this;
        }

        public Criteria andVehicleOwnerIdLessThan(Integer value) {
            addCriterion("vehicle_owner_ID <", value, "vehicleOwnerId");
            return (Criteria) this;
        }

        public Criteria andVehicleOwnerIdLessThanOrEqualTo(Integer value) {
            addCriterion("vehicle_owner_ID <=", value, "vehicleOwnerId");
            return (Criteria) this;
        }

        public Criteria andVehicleOwnerIdIn(List<Integer> values) {
            addCriterion("vehicle_owner_ID in", values, "vehicleOwnerId");
            return (Criteria) this;
        }

        public Criteria andVehicleOwnerIdNotIn(List<Integer> values) {
            addCriterion("vehicle_owner_ID not in", values, "vehicleOwnerId");
            return (Criteria) this;
        }

        public Criteria andVehicleOwnerIdBetween(Integer value1, Integer value2) {
            addCriterion("vehicle_owner_ID between", value1, value2, "vehicleOwnerId");
            return (Criteria) this;
        }

        public Criteria andVehicleOwnerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vehicle_owner_ID not between", value1, value2, "vehicleOwnerId");
            return (Criteria) this;
        }

        public Criteria andVehicleStateIsNull() {
            addCriterion("vehicle_state is null");
            return (Criteria) this;
        }

        public Criteria andVehicleStateIsNotNull() {
            addCriterion("vehicle_state is not null");
            return (Criteria) this;
        }

        public Criteria andVehicleStateEqualTo(Integer value) {
            addCriterion("vehicle_state =", value, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateNotEqualTo(Integer value) {
            addCriterion("vehicle_state <>", value, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateGreaterThan(Integer value) {
            addCriterion("vehicle_state >", value, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("vehicle_state >=", value, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateLessThan(Integer value) {
            addCriterion("vehicle_state <", value, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateLessThanOrEqualTo(Integer value) {
            addCriterion("vehicle_state <=", value, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateIn(List<Integer> values) {
            addCriterion("vehicle_state in", values, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateNotIn(List<Integer> values) {
            addCriterion("vehicle_state not in", values, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateBetween(Integer value1, Integer value2) {
            addCriterion("vehicle_state between", value1, value2, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andVehicleStateNotBetween(Integer value1, Integer value2) {
            addCriterion("vehicle_state not between", value1, value2, "vehicleState");
            return (Criteria) this;
        }

        public Criteria andLicensePlateIsNull() {
            addCriterion("License_plate is null");
            return (Criteria) this;
        }

        public Criteria andLicensePlateIsNotNull() {
            addCriterion("License_plate is not null");
            return (Criteria) this;
        }

        public Criteria andLicensePlateEqualTo(String value) {
            addCriterion("License_plate =", value, "licensePlate");
            return (Criteria) this;
        }

        public Criteria andLicensePlateNotEqualTo(String value) {
            addCriterion("License_plate <>", value, "licensePlate");
            return (Criteria) this;
        }

        public Criteria andLicensePlateGreaterThan(String value) {
            addCriterion("License_plate >", value, "licensePlate");
            return (Criteria) this;
        }

        public Criteria andLicensePlateGreaterThanOrEqualTo(String value) {
            addCriterion("License_plate >=", value, "licensePlate");
            return (Criteria) this;
        }

        public Criteria andLicensePlateLessThan(String value) {
            addCriterion("License_plate <", value, "licensePlate");
            return (Criteria) this;
        }

        public Criteria andLicensePlateLessThanOrEqualTo(String value) {
            addCriterion("License_plate <=", value, "licensePlate");
            return (Criteria) this;
        }

        public Criteria andLicensePlateLike(String value) {
            addCriterion("License_plate like", value, "licensePlate");
            return (Criteria) this;
        }

        public Criteria andLicensePlateNotLike(String value) {
            addCriterion("License_plate not like", value, "licensePlate");
            return (Criteria) this;
        }

        public Criteria andLicensePlateIn(List<String> values) {
            addCriterion("License_plate in", values, "licensePlate");
            return (Criteria) this;
        }

        public Criteria andLicensePlateNotIn(List<String> values) {
            addCriterion("License_plate not in", values, "licensePlate");
            return (Criteria) this;
        }

        public Criteria andLicensePlateBetween(String value1, String value2) {
            addCriterion("License_plate between", value1, value2, "licensePlate");
            return (Criteria) this;
        }

        public Criteria andLicensePlateNotBetween(String value1, String value2) {
            addCriterion("License_plate not between", value1, value2, "licensePlate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vehicle
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 06 18:33:15 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}