package com.bishe.smartcommunity.vehicle.domain;

import java.io.Serializable;

public class Vehicle implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.vehicle_id
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    private Integer vehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.vehicle_owner_ID
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    private Integer vehicleOwnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.vehicle_state
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    private Integer vehicleState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.License_plate
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    private String licensePlate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vehicle
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.vehicle_id
     *
     * @return the value of vehicle.vehicle_id
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public Integer getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.vehicle_id
     *
     * @param vehicleId the value for vehicle.vehicle_id
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public void setVehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.vehicle_owner_ID
     *
     * @return the value of vehicle.vehicle_owner_ID
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public Integer getVehicleOwnerId() {
        return vehicleOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.vehicle_owner_ID
     *
     * @param vehicleOwnerId the value for vehicle.vehicle_owner_ID
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public void setVehicleOwnerId(Integer vehicleOwnerId) {
        this.vehicleOwnerId = vehicleOwnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.vehicle_state
     *
     * @return the value of vehicle.vehicle_state
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public Integer getVehicleState() {
        return vehicleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.vehicle_state
     *
     * @param vehicleState the value for vehicle.vehicle_state
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public void setVehicleState(Integer vehicleState) {
        this.vehicleState = vehicleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.License_plate
     *
     * @return the value of vehicle.License_plate
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public String getLicensePlate() {
        return licensePlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.License_plate
     *
     * @param licensePlate the value for vehicle.License_plate
     *
     * @mbg.generated Sat Mar 06 18:33:15 CST 2021
     */
    public void setLicensePlate(String licensePlate) {
        this.licensePlate = licensePlate == null ? null : licensePlate.trim();
    }
}